### ISSUE TITLE
Any plans for TBC (2.5.1+)?

### ISSUE THREAD

**Issue by ghost** [mooreatv/NeatMinimap#18]
More than ever needed, as they added one extra feature to minimap, similar to questie feature that you can see where is closest flightpath, mailbox etc.

To me it looks like just useless feature, similar to rest minimap features.

PTR (Classic) is now updated 2.5.1 so any can test now TBC before prepatch in 18th May.

**Comment by mooreatv** [comment]
It should be working already, no?

**Comment by ghost** [comment]
Which version supports 2.5.1?

**Comment by mooreatv** [comment]
It's the same code, so either, but just keep classic (load outdated) and it'll work fine

**Comment by ghost** [comment]
At first look, it looks like it does work overall.

But then, wanted change settings such as square minimap, but minimap went "corrupted" state, map area disappeared from minimap, tried to revert settings back and reload but it was still same, had to remove addon and use addon on default settings.

I can add screenshot later today, or video about problem.

**Comment by ghost** [comment]
Here video of the problem:
https://imgur.com/WpeLcmv

**Comment by mooreatv** [comment]
Square minimap is actually not really implemented (if you mouse over it says experimental; also if you reload it doesn't "stick" 

I should just remove that checkbox for now (was for me while experimenting)

**Comment by mooreatv** [comment]
fixed in v1.07.06 - thx !
