### ISSUE TITLE
[classic]sticky button

### ISSUE THREAD

**Issue by iron217** [mooreatv/NeatMinimap#9]
https://drive.google.com/file/d/1kZaJVDGMKTfh-qiV5XnUrpq_FWRdvb3S/view?usp=sharing

**Comment by mooreatv** [comment]
first thanks for taking the time to report this and even making a video to explain the issue!

second I did notice this once and I had to /reload to get rid of it but I don't know exactly how it happens - I think it has to do with starting to drag a button away from the minimap and it's hidden and then stuck

I need to look some more (do you have a way to trigger it consistently?)

**Comment by iron217** [comment]
> first thanks for taking the time to report this and even making a video to explain the issue!
> 
> second I did notice this once and I had to /reload to get rid of it but I don't know exactly how it happens - I think it has to do with starting to drag a button away from the minimap and it's hidden and then stuck
> 
> I need to look some more (do you have a way to trigger it consistently?)

shift + left mouse cursor is pulled to the side until the buttons on the minimap disappear, return back and you see that the cursor is stuck

**Comment by iron217** [comment]
to fix it, you can still hold down the left mouse button and start dragging the mouse to the side while remaining on the minimap

https://drive.google.com/file/d/1QZUQPjHquwCUZbsCwLGvVSMzUXVQ6guT/view?usp=sharing

**Comment by mooreatv** [comment]
yeah was just going to post a workaround which to redo what started the issue (like shift drag for questie etc)

I'm trying to find how to detect a frame is being dragged but haven't found yet

**Comment by iron217** [comment]
> yeah was just going to post a workaround which to redo what started the issue (like shift drag for questie etc)
> 
> I'm trying to find how to detect a frame is being dragged but haven't found yet

I hope I have helped you enough

**Comment by mooreatv** [comment]
got a fix idea and implemented it, it works; thanks to @Meorawr

**Comment by mooreatv** [comment]
fixed in 1.5, please confirm it indeed solves it for you as well and thanks again for the detailed report and help

**Comment by iron217** [comment]
> fixed in 1.5, please confirm it indeed solves it for you as well and thanks again for the detailed report and help

problem not found great job

**Comment by iron217** [comment]
> > fixed in 1.5, please confirm it indeed solves it for you as well and thanks again for the detailed report and help
> 
> problem not found great job

the truth is now a small problem localization has flown, I also updated the translation of new options on the site
